jobs:
  - reduce_sectors:
       reduce:
       - {{topologies: [basis], sectors: [b{"".join("1" if s else "0" for s in p.top_sector)}], r: {p.maxr}, s: {p.maxs}}}
       select_integrals:
        select_mandatory_list:
         - [basis, "integrals"]
       run_initiate: true
       run_triangular: true
       run_back_substitution: true
  - kira2math:
       target:
         - [basis, "integrals"]
       reconstruct_mass: false
