jobs:
  - reduce_sectors:
       reduce:
       - {{r: {p.maxr}, s: {p.maxs}}}
       select_integrals:
        select_mandatory_list:
         - [basis, "integrals"]
       run_initiate: true
       run_triangular: true
       run_back_substitution: true
  - kira2math:
       target:
         - [basis, "integrals"]
