jobs:
  - reduce_sectors:
       reduce:
       - {r: 6, s: 2}
       select_integrals:
        select_mandatory_recursively:
        - {r: 6, s: 2} 
       run_initiate: true
       run_triangular: true
       run_back_substitution: true
  - kira2math:
       target:
        - {topologies: [box], sectors: [15], r: 6, s: 2}
