jobs:
 - reduce_sectors:
    reduce:
    - {{topologies: [basis], sectors: [b{"".join("1" if s else "0" for s in p.top_sector)}], r: {p.maxr}, s: {p.maxs}}}
    select_integrals:
     select_mandatory_list:
      - [basis, "integrals"]
#% if p.preferred_masters:
    preferred_masters: "preferred-masters"
#% pass
    integral_ordering: 8
    run_symmetries: true
    run_initiate: input
    run_triangular: false
    run_back_substitution: false
    run_firefly: false
