kinematics:
  incoming_momenta: [p1, p2, p3, p4]
  outgoing_momenta: []
  momentum_conservation: [p4, -p1-p2-p3]
  kinematic_invariants:
    - [s12, 2] 
    - [s23, 2] 
    - [m2,  2]
  scalarproduct_rules:
    - [[p1,p1], 0] 
    - [[p2,p2], 0]
    - [[p3,p3], 0]
    - [[p4,p4], 0]
    - [[p1+p2, p1+p2], s12]
    - [[p1+p3, p1+p3], -s12-s23] 
    - [[p2+p3, p2+p3], s23]
  symbol_to_replace_by_one: m2
