integralfamilies:
  - name: "basis"
    loop_momenta:
#% for m in p.loop_momenta:
      - {m!r}
#% pass
    top_level_sectors: [{p.top_sector}]
    propagators:
#% for mom, m2 in p.denominators:
      - [{mom!r}, {m2!r}]
#% pass
